### ISSUE TITLE
Doesn't seem to be working

### ISSUE THREAD

**Issue by blinkwayne** [Babinsky/community_store_square#1]
I have this gateway installed, but when I go through the check out process there is never a point when I am asked for payment info other than billing address.

I do have a square api key & id etc..., and I am currently in sandbox mode.

Using Concrete V8.0.3
Community Store V 1.0.7
Square Payment Method 0.9.1

**Comment by Babinsky** [comment]
Hi, can you please check if you have SSL ? I think square does require this and if you do not have https enabled, it does not open the fields to enter the credit card number, CVV and such.
You can enable the developer tools to verify if this is the case.
Regards
:-) Babinsky

**Comment by blinkwayne** [comment]
Thanks for building this and also thanks for responding to this issue :)

I do have SSL and valid certificate  installed
I am using both htaccess  and Concrete5 Dashboard based Canonical URL redirect to put the entire site under https

I was also able to login to the hosting server via shell and successfully send the locations command and receive the response.

**Comment by Babinsky** [comment]
So you are saying it still does not work? What about the output from the developer tools?

**Comment by blinkwayne** [comment]
it is still not working. I was able to get output to list the locations after logging into the remote sever via shell using: 

`curl -H "Authorization: Bearer PERSONAL_ACCESS_TOKEN" https://connect.squareup.com/v2/locations`

using the sandbox access token to get my sandbox location output and live access token to get the live location output too.

**Comment by Babinsky** [comment]
Any errors visible in the developer tools? Or in the front end?

The workflow of the community store is:

Checkout -> Billing Address fill in -> Payment selection if multiple methods are activated -> Payment (Credit Card details) -> Complete Order -> Confirmation (mails) that order has been placed.

Please send me print screens to me: barbara.hegnauer(at)webgate.biz

**Comment by blinkwayne** [comment]
Ok I did some testing. I started with a fresh vanilla install of C5 V8.0.3 using the default theme. 

The payment form is not loading correctly in Firefox.

Everything is working great in Safari, I was able to input all the Payment info and complete the transaction.

I have not tested Chrome yet.

But in FF V51.0 64 bit, the Credit Card details area is only displaying the labels and not the input fields. See attached screen cap

If I use Developer Tools and "Inspect Element" the input fields will then become visible on the page.

![scrncap](https://cloud.githubusercontent.com/assets/366238/22264125/c228e75a-e22b-11e6-98df-e03937b609ca.jpg)

**Comment by Babinsky** [comment]
Hi, the error is reproducible. Thanks for investigating. In chrome it works. I am talking to the vendor.

**Comment by Babinsky** [comment]
Hank from Square support confirmed the bug. Should be fixed with the next update.

**Comment by blinkwayne** [comment]
Thanks for your work on this, extremely helpful :)

**Comment by blinkwayne** [comment]
Has there been any word on the update that will fix this issue yet?
