### ISSUE TITLE
Payment/Order not processing at checkout

### ISSUE THREAD

**Issue by FortyNinjaFISH** [Babinsky/community_store_square#5]
I'm having an issue on a store (https://www.jigsawlearning.ca/store) where during checkout after payment information has been added the following error appears: 
`Something went wrong during the payment process!`

I also get the following error in the C5 Logs:
`Something went wrong during the payment process:SquareConnect\ApiException: [HTTP/1.1 301 Moved Permanently] in /home/jigsawlearning/public_html/packages/community_store_square/vendor/square/connect/lib/ApiClient.php:262
Stack trace:
#0 /home/jigsawlearning/public_html/packages/community_store_square/vendor/square/connect/lib/Api/TransactionApi.php(317): SquareConnect\ApiClient->callApi('/v2/locations/h...', 'POST', Array, '{"card_nonce":"...', Array, '\\SquareConnect\\...')
#1 /home/jigsawlearning/public_html/packages/community_store_square/vendor/square/connect/lib/Api/TransactionApi.php(236): SquareConnect\Api\TransactionApi->chargeWithHttpInfo('EAAAEGyU0FQjxuj...', 'http://www.jig...', Array)
#2 /home/jigsawlearning/public_html/packages/community_store_square/src/CommunityStore/Payment/Methods/CommunityStoreSquare/CommunityStoreSquarePaymentMethod.php(136): SquareConnect\Api\TransactionApi->charge('EAAAEGyU0FQjxuj...', 'http://www.jig...', Array)
#3 /home/jigsawlearning/public_html/packages/community_store/src/CommunityStore/Payment/Method.php(241): Concrete\Package\CommunityStoreSquare\Src\CommunityStore\Payment\Methods\CommunityStoreSquare\CommunityStoreSquarePaymentMethod->submitPayment()
#4 /home/jigsawlearning/public_html/packages/community_store/controllers/single_page/checkout.php(244): Concrete\Package\CommunityStore\Src\CommunityStore\Payment\Method->submitPayment()
#5 [internal function]: Concrete\Package\CommunityStore\Controller\SinglePage\Checkout->submit()
#6 /home/jigsawlearning/public_html/concrete/src/Controller/AbstractController.php(161): call_user_func_array(Array, Array)
#7 /home/jigsawlearning/public_html/concrete/src/Routing/DispatcherRouteCallback.php(211): Concrete\Core\Controller\AbstractController->runAction('submit', Array)
#8 /home/jigsawlearning/public_html/concrete/src/Application/Application.php(449): Concrete\Core\Routing\DispatcherRouteCallback->execute(Object(Concrete\Core\Http\Request))
#9 /home/jigsawlearning/public_html/concrete/bootstrap/start.php(305): Concrete\Core\Application\Application->dispatch(Object(Concrete\Core\Http\Request))
#10 /home/jigsawlearning/public_html/concrete/dispatcher.php(36): require('/home/jigsawlea...')
#11 /home/jigsawlearning/public_html/index.php(2): require('/home/jigsawlea...')
#12 {main}`

- Even with payments set to live or sandbox the error occurs.
- I have added Tokens and Appliation ID for live and sandbox to the store.
- Square Account is using the latest API version.
- Community Store v1.4.2 / Square Payment Method v.0.9.1

Any assistant would be great!

**Comment by FortyNinjaFISH** [comment]
Bump- would appreciate any assistance with this.

**Comment by FortyNinjaFISH** [comment]
Would the issue lie with the first line:
`Something went wrong during the payment process:SquareConnect\ApiException: [HTTP/1.1 301 Moved Permanently`

I have the site set to use HTTPS- is the app having issue with this?

**Comment by Babinsky** [comment]
Hi Jason,
 
Not sure what the problem might be and unfortunately, the web site I developed this for is not in use anymore.
 
According to this line:
Something went wrong during the payment process:SquareConnect\ApiException: [HTTP/1.1 301 Moved Permanently] in
 
I am not sure but I can imagine that square changed something on their side?
 
On the website of square there is a whole section "API Developer" and there is the description about how to use their interface.
 
Regards,
:-) Barbara

**Comment by FortyNinjaFISH** [comment]
Hopefully i can figure this out! 
*brews a pot of coffee, and adds novice Square API developer to his resume* - haha
